import type { ProductDoc } from '@/db/schemas';

export const PRODUCTS: ProductDoc[] = [
  {
    product_id: 'base_6',
    type: 'digital',
    title: 'База (6 уроків)',
    description:
      'Усі 6 уроків: як шукати роботу, резюме, LinkedIn, співбесіди, складні питання, зарплата.',
    price: 960,
    currency: 'UAH',
    visible: true,
    lessons: [
      'lesson_search',
      'lesson_resume',
      'lesson_linkedin',
      'lesson_interview',
      'lesson_hard_qs',
      'lesson_salary',
    ],
    order: 1,
    created_at: new Date(),
  },
  {
    product_id: 'lesson_search',
    type: 'digital',
    title: 'Урок: Пошук роботи',
    description: 'Як шукати роботу: канали, нетворкінг, прямі контакти з компаніями.',
    price: 200,
    currency: 'UAH',
    visible: true,
    lessons: ['lesson_search'],
    order: 10,
    created_at: new Date(),
  },
  {
    product_id: 'lesson_resume',
    type: 'digital',
    title: 'Урок: Резюме',
    description: 'Як показати досвід сильніше і обійти типові помилки.',
    price: 200,
    currency: 'UAH',
    visible: true,
    lessons: ['lesson_resume'],
    order: 11,
    created_at: new Date(),
  },
  {
    product_id: 'lesson_linkedin',
    type: 'digital',
    title: 'Урок: LinkedIn',
    description: 'Як зробити LinkedIn інструментом, який приносить пропозиції.',
    price: 200,
    currency: 'UAH',
    visible: true,
    lessons: ['lesson_linkedin'],
    order: 12,
    created_at: new Date(),
  },
  {
    product_id: 'lesson_interview',
    type: 'digital',
    title: 'Урок: Співбесіди',
    description: 'Як готуватись і як говорити, щоб брати після першої зустрічі.',
    price: 200,
    currency: 'UAH',
    visible: true,
    lessons: ['lesson_interview'],
    order: 13,
    created_at: new Date(),
  },
  {
    product_id: 'lesson_hard_qs',
    type: 'digital',
    title: 'Урок: Складні питання',
    description: 'Відповіді на незручні питання спокійно і по суті.',
    price: 200,
    currency: 'UAH',
    visible: true,
    lessons: ['lesson_hard_qs'],
    order: 14,
    created_at: new Date(),
  },
  {
    product_id: 'lesson_salary',
    type: 'digital',
    title: 'Урок: Зарплата',
    description: 'Оцінити вартість, говорити про гроші і вести перемовини.',
    price: 200,
    currency: 'UAH',
    visible: true,
    lessons: ['lesson_salary'],
    order: 15,
    created_at: new Date(),
  },
  {
    product_id: 'consult_profession',
    type: 'appointment',
    title: 'Профорієнтація',
    description: 'Онлайн-зустріч ~60 хв. Розбір напрямку індивідуально під тебе.',
    price: 1000,
    currency: 'UAH',
    visible: true,
    order: 20,
    created_at: new Date(),
  },
  {
    product_id: 'consult_career',
    type: 'appointment',
    title: 'Кар’єрна консультація',
    description:
      'Онлайн-зустріч ~1,5 години з сертифікованим кар’єрним консультантом. Розбір ситуації і план змін.',
    price: 2000,
    currency: 'UAH',
    visible: true,
    order: 21,
    created_at: new Date(),
  },
  {
    product_id: 'system_path',
    type: 'appointment',
    title: 'Системний шлях до роботи',
    description:
      'Повний пакет: база уроків + профорієнтація + кар’єрна консультація + передача профілю роботодавцю.',
    price: 150,
    currency: 'USD',
    visible: true,
    order: 22,
    created_at: new Date(),
  },
];
